In [81]:
import pandas as pd
billings_df= pd.read_csv('billings.csv')



display(billings_df)

C:\Users\GokulkannaML\AppData\Local\Temp\ipykernel_17308\2086764334.py:2: DtypeWarning: Columns (0: Proforma_Auto_Renewal, 1: Proforma_World_Pay_Token, 2: Current_Anchor_List, 3: Last_Renewal, 4: Last_Band) have mixed types. Specify dtype option on import or set low_memory=False.
  billings_df= pd.read_csv('billings.csv')

,Co_Ref,Renewal_Month,Connection_Net,Connection_Qty,Discount_Amount,Sustainability_Score,Total_Renewal_Score_New,Starting_Connection_Net,Starting_Connection_Qty,Last_Years_Price,...,Connection_Group,Tenure_Group,#_of_Connection,Last_Renewal,Last_Band,Last_Total_Net_Paid,Last_Connections,Anchor_Group,Renewal_Year,DateTime_Out
0,VT6174,01-11-2024,NaN,NaN,NaN,8.0,42.5,NaN,NaN,799.0,...,1,3,1.0,01-11-2023,Band B,664.0,1.0,1,2024,01-11-2024
1,VD3828,01-08-2025,NaN,NaN,NaN,8.0,41.5,NaN,NaN,799.0,...,1,1,1.0,NaN,NaN,NaN,NaN,1,2025,01-08-2025
2,DV8120,01-03-2025,NaN,NaN,NaN,8.0,33.0,NaN,NaN,799.0,...,1,4+,1.0,01-03-2024,Band C1,749.0,1.0,1,2025,01-03-2025
3,EZ9894,01-06-2025,NaN,NaN,NaN,9.5,44.5,NaN,NaN,799.0,...,1,4+,1.0,01-06-2024,Band C1,749.0,1.0,1,2025,01-06-2025
4,FA8957,01-03-2025,NaN,NaN,NaN,9.5,42.5,NaN,NaN,799.0,...,1,3,1.0,01-03-2024,Band C1,749.0,1.0,1,2025,01-03-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122077,VI6211,01-04-2023,NaN,NaN,NaN,8.0,33.5,NaN,NaN,539.0,...,Independent,3,0.0,NaN,NaN,NaN,NaN,Independent,2023,01-04-2023
122078,NI7208,01-06-2023,NaN,NaN,NaN,8.0,30.5,NaN,NaN,539.0,...,Independent,3,0.0,NaN,NaN,NaN,NaN,Independent,2023,01-06-2023
122079,DO6023,01-09-2023,NaN,NaN,NaN,8.0,33.0,NaN,NaN,539.0,...,Independent,3,0.0,NaN,NaN,NaN,NaN,Independent,2023,01-09-2023
122080,KR5815,01-08-2023,NaN,NaN,NaN,8.0,40.5,NaN,NaN,539.0,...,Independent,3,0.0,NaN,NaN,NaN,NaN,Independent,2023,01-08-2023
122081,MA8737,01-07-2023,NaN,NaN,NaN,8.0,42.5,NaN,NaN,539.0,...,Independent,3,0.0,NaN,NaN,NaN,NaN,Independent,2023,01-07-2023

In [82]:
billings_df.describe()

,Connection_Net,Connection_Qty,Sustainability_Score,Total_Renewal_Score_New,Starting_Connection_Net,Starting_Connection_Qty,Last_Years_Price,Last_Years_Date_Paid,Auto_Renewal_Score,Status_Scores,...,Membership_Net,Package_Net,PQQNet,Total_Net_Paid,Amount,Total_Amount,#_of_Connection,Last_Total_Net_Paid,Last_Connections,Renewal_Year
count,8037.000000,8037.000000,122082.000000,122082.000000,8545.000000,8545.000000,112992.000000,0.0,122082.000000,122082.000000,...,122082.000000,122082.000000,122082.000000,101226.000000,122082.000000,122082.000000,121956.000000,73726.000000,73702.000000,122082.000000
mean,418.268259,5.799925,8.619530,41.983319,463.591223,6.419310,1063.854763,NaN,8.479506,7.187685,...,848.107740,60.233556,133.188996,1077.907507,1107.750864,1069.066063,3.198670,993.923497,3.547773,2024.300290
std,623.568386,7.608354,0.692765,4.291603,685.366345,8.401839,694.584676,NaN,0.499582,3.263780,...,533.440504,67.069747,48.608783,651.303068,689.139920,675.506405,6.548384,518.252054,6.951354,1.029394
min,55.000000,1.000000,8.000000,30.500000,55.000000,1.000000,0.000000,NaN,8.000000,0.000000,...,0.000000,0.000000,-529.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2023.000000
25%,99.000000,1.000000,8.000000,41.500000,110.000000,2.000000,664.000000,NaN,8.000000,7.000000,...,500.000000,0.000000,99.000000,684.000000,699.000000,684.000000,1.000000,684.000000,1.000000,2023.000000
50%,220.000000,3.000000,8.000000,43.500000,225.000000,3.000000,919.000000,NaN,8.000000,9.000000,...,674.000000,0.000000,135.000000,924.000000,934.000000,919.000000,1.000000,869.000000,2.000000,2024.000000
75%,474.000000,7.000000,9.500000,45.000000,495.000000,7.000000,1264.000000,NaN,9.000000,9.000000,...,1014.000000,120.000000,135.000000,1269.000000,1274.000000,1239.000000,3.000000,1149.000000,4.000000,2025.000000
max,4752.000000,48.000000,9.500000,46.500000,4752.000000,48.000000,18326.000000,NaN,9.000000,9.000000,...,13245.000000,225.000000,1930.000000,18326.000000,19927.000000,18326.000000,197.000000,12616.000000,197.000000,2050.000000

In [83]:
columns= billings_df.columns
total_count=len(billings_df)
columns_with_min_null=[]
removed=[]
for x in columns:
   
    null_count= (billings_df[x].isnull().sum())
    print(x ,"   ", "Total count:" , total_count,"   ", "NUll :", null_count , end="  |  ")
    percent =(null_count/total_count)*100
    if(percent<25):
        columns_with_min_null.append(x)
    else :
        removed.append(x)
    print()
print(columns_with_min_null)
print(removed)



# print(columns)

Co_Ref     Total count: 122082     NUll : 0  |
Renewal_Month     Total count: 122082     NUll : 0  |
Connection_Net     Total count: 122082     NUll : 114045  |
Connection_Qty     Total count: 122082     NUll : 114045  |
Discount_Amount     Total count: 122082     NUll : 108531  |
Sustainability_Score     Total count: 122082     NUll : 0  |
Total_Renewal_Score_New     Total count: 122082     NUll : 0  |
Starting_Connection_Net     Total count: 122082     NUll : 113537  |
Starting_Connection_Qty     Total count: 122082     NUll : 113537  |
Last_Years_Price     Total count: 122082     NUll : 9090  |
Last_Years_Date_Paid     Total count: 122082     NUll : 122082  |
Auto_Renewal_Score     Total count: 122082     NUll : 0  |
Status_Scores     Total count: 122082     NUll : 0  |
Anchoring_Score     Total count: 122082     NUll : 0  |
Tenure_Scores     Total count: 122082     NUll : 0  |
Proforma_Auto_Renewal     Total count: 122082     NUll : 18052  |
Proforma_World_Pay_Token     Total count: 122082     NUll : 18052  |
Proforma_Date     Total count: 122082     NUll : 304  |
Current_Anchorings     Total count: 122082     NUll : 0  |
Current_Anchor_List     Total count: 122082     NUll : 25957  |
Payment_Timeframe     Total count: 122082     NUll : 20856  |
Registration_Date     Total count: 122082     NUll : 1018  |
Proforma_Account_Stage     Total count: 122082     NUll : 9229  |
Proforma_Audit_Status     Total count: 122082     NUll : 9229  |
Current_Auto_Renewal_Flag     Total count: 122082     NUll : 0  |
Current_World_Pay_Token     Total count: 122082     NUll : 0  |
Renewal_Score_At_Release     Total count: 122082     NUll : 126  |
Proforma_Membership_Status     Total count: 122082     NUll : 126  |
Proforma_Approved_Lists     Total count: 122082     NUll : 126  |
Tenure_Years     Total count: 122082     NUll : 1018  |
Band     Total count: 122082     NUll : 24  |
Prospect_Renewal_Date     Total count: 122082     NUll : 0  |
Closed_Date     Total count: 122082     NUll : 8188  |
Prospect_Status     Total count: 122082     NUll : 0  |
Starting_Net     Total count: 122082     NUll : 0  |
Starting_Vat     Total count: 122082     NUll : 0  |
Starting_Gross     Total count: 122082     NUll : 0  |
Starting_Membership_Net     Total count: 122082     NUll : 0  |
Starting_Package_Net     Total count: 122082     NUll : 0  |
Starting_PQQ_Net     Total count: 122082     NUll : 0  |
Gross     Total count: 122082     NUll : 0  |
Membership_Net     Total count: 122082     NUll : 0  |
Package_Net     Total count: 122082     NUll : 0  |
PQQNet     Total count: 122082     NUll : 0  |
Total_Net_Paid     Total count: 122082     NUll : 20856  |
Prospect_Outcome     Total count: 122082     NUll : 0  |
Payment_Method     Total count: 122082     NUll : 0  |
Amount     Total count: 122082     NUll : 0  |
Total_Amount     Total count: 122082     NUll : 0  |
Connection_Group     Total count: 122082     NUll : 126  |
Tenure_Group     Total count: 122082     NUll : 1018  |
#_of_Connection     Total count: 122082     NUll : 126  |
Last_Renewal     Total count: 122082     NUll : 48291  |
Last_Band     Total count: 122082     NUll : 48311  |
Last_Total_Net_Paid     Total count: 122082     NUll : 48356  |
Last_Connections     Total count: 122082     NUll : 48380  |
Anchor_Group     Total count: 122082     NUll : 126  |
Renewal_Year     Total count: 122082     NUll : 0  |
DateTime_Out     Total count: 122082     NUll : 0  |
['Co_Ref', 'Renewal_Month', 'Sustainability_Score', 'Total_Renewal_Score_New', 'Last_Years_Price', 'Auto_Renewal_Score', 'Status_Scores', 'Anchoring_Score', 'Tenure_Scores', 'Proforma_Auto_Renewal', 'Proforma_World_Pay_Token', 'Proforma_Date', 'Current_Anchorings', 'Current_Anchor_List', 'Payment_Timeframe', 'Registration_Date', 'Proforma_Account_Stage', 'Proforma_Audit_Status', 'Current_Auto_Renewal_Flag', 'Current_World_Pay_Token', 'Renewal_Score_At_Release', 'Proforma_Membership_Status', 'Proforma_Approved_Lists', 'Tenure_Years', 'Band', 'Prospect_Renewal_Date', 'Closed_Date', 'Prospect_Status', 'Starting_Net', 'Starting_Vat', 'Starting_Gross', 'Starting_Membership_Net', 'Starting_Package_Net', 'Starting_PQQ_Net', 'Gross', 'Membership_Net', 'Package_Net', 'PQQNet', 'Total_Net_Paid', 'Prospect_Outcome', 'Payment_Method', 'Amount', 'Total_Amount', 'Connection_Group', 'Tenure_Group', '#_of_Connection', 'Anchor_Group', 'Renewal_Year', 'DateTime_Out']
['Connection_Net', 'Connection_Qty', 'Discount_Amount', 'Starting_Connection_Net', 'Starting_Connection_Qty', 'Last_Years_Date_Paid', 'Last_Renewal', 'Last_Band', 'Last_Total_Net_Paid', 'Last_Connections']

In [84]:
useable_df=billings_df[columns_with_min_null]
display(useable_df)

,Co_Ref,Renewal_Month,Sustainability_Score,Total_Renewal_Score_New,Last_Years_Price,Auto_Renewal_Score,Status_Scores,Anchoring_Score,Tenure_Scores,Proforma_Auto_Renewal,...,Prospect_Outcome,Payment_Method,Amount,Total_Amount,Connection_Group,Tenure_Group,#_of_Connection,Anchor_Group,Renewal_Year,DateTime_Out
0,VT6174,01-11-2024,8.0,42.5,799.0,9,9,7.5,9.0,True,...,Won,CARD,919,799.0,1,3,1.0,1,2024,01-11-2024
1,VD3828,01-08-2025,8.0,41.5,799.0,9,9,7.5,8.0,True,...,Won,CARD,919,799.0,1,1,1.0,1,2025,01-08-2025
2,DV8120,01-03-2025,8.0,33.0,799.0,8,0,7.5,9.5,True,...,Won,CARD,799,799.0,1,4+,1.0,1,2025,01-03-2025
3,EZ9894,01-06-2025,9.5,44.5,799.0,9,9,7.5,9.5,True,...,Won,CARD,799,799.0,1,4+,1.0,1,2025,01-06-2025
4,FA8957,01-03-2025,9.5,42.5,799.0,9,8,7.5,8.5,True,...,Won,CARD,799,799.0,1,3,1.0,1,2025,01-03-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122077,VI6211,01-04-2023,8.0,33.5,539.0,9,0,7.5,9.0,NaN,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-04-2023
122078,NI7208,01-06-2023,8.0,30.5,539.0,8,0,7.5,7.0,NaN,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-06-2023
122079,DO6023,01-09-2023,8.0,33.0,539.0,9,0,7.5,8.5,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-09-2023
122080,KR5815,01-08-2023,8.0,40.5,539.0,9,7,7.5,9.0,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-08-2023
122081,MA8737,01-07-2023,8.0,42.5,539.0,9,9,7.5,9.0,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-07-2023

In [85]:
columns= useable_df.columns
total_count=len(useable_df)
columns_with_min_null=[]
for x in columns:
   
    null_count= (billings_df[x].isnull().sum())
    print(x ,"   ", "Total count:" , total_count,"   ", "NUll :", null_count , end="  |  ")
    print()

Co_Ref     Total count: 122082     NUll : 0  |
Renewal_Month     Total count: 122082     NUll : 0  |
Sustainability_Score     Total count: 122082     NUll : 0  |
Total_Renewal_Score_New     Total count: 122082     NUll : 0  |
Last_Years_Price     Total count: 122082     NUll : 9090  |
Auto_Renewal_Score     Total count: 122082     NUll : 0  |
Status_Scores     Total count: 122082     NUll : 0  |
Anchoring_Score     Total count: 122082     NUll : 0  |
Tenure_Scores     Total count: 122082     NUll : 0  |
Proforma_Auto_Renewal     Total count: 122082     NUll : 18052  |
Proforma_World_Pay_Token     Total count: 122082     NUll : 18052  |
Proforma_Date     Total count: 122082     NUll : 304  |
Current_Anchorings     Total count: 122082     NUll : 0  |
Current_Anchor_List     Total count: 122082     NUll : 25957  |
Payment_Timeframe     Total count: 122082     NUll : 20856  |
Registration_Date     Total count: 122082     NUll : 1018  |
Proforma_Account_Stage     Total count: 122082     NUll : 9229  |
Proforma_Audit_Status     Total count: 122082     NUll : 9229  |
Current_Auto_Renewal_Flag     Total count: 122082     NUll : 0  |
Current_World_Pay_Token     Total count: 122082     NUll : 0  |
Renewal_Score_At_Release     Total count: 122082     NUll : 126  |
Proforma_Membership_Status     Total count: 122082     NUll : 126  |
Proforma_Approved_Lists     Total count: 122082     NUll : 126  |
Tenure_Years     Total count: 122082     NUll : 1018  |
Band     Total count: 122082     NUll : 24  |
Prospect_Renewal_Date     Total count: 122082     NUll : 0  |
Closed_Date     Total count: 122082     NUll : 8188  |
Prospect_Status     Total count: 122082     NUll : 0  |
Starting_Net     Total count: 122082     NUll : 0  |
Starting_Vat     Total count: 122082     NUll : 0  |
Starting_Gross     Total count: 122082     NUll : 0  |
Starting_Membership_Net     Total count: 122082     NUll : 0  |
Starting_Package_Net     Total count: 122082     NUll : 0  |
Starting_PQQ_Net     Total count: 122082     NUll : 0  |
Gross     Total count: 122082     NUll : 0  |
Membership_Net     Total count: 122082     NUll : 0  |
Package_Net     Total count: 122082     NUll : 0  |
PQQNet     Total count: 122082     NUll : 0  |
Total_Net_Paid     Total count: 122082     NUll : 20856  |
Prospect_Outcome     Total count: 122082     NUll : 0  |
Payment_Method     Total count: 122082     NUll : 0  |
Amount     Total count: 122082     NUll : 0  |
Total_Amount     Total count: 122082     NUll : 0  |
Connection_Group     Total count: 122082     NUll : 126  |
Tenure_Group     Total count: 122082     NUll : 1018  |
#_of_Connection     Total count: 122082     NUll : 126  |
Anchor_Group     Total count: 122082     NUll : 126  |
Renewal_Year     Total count: 122082     NUll : 0  |
DateTime_Out     Total count: 122082     NUll : 0  |

In [96]:
numerical_columns = useable_df.select_dtypes(include=['int64', 'float64']).columns
display(numerical_columns)

for col in numerical_columns:
    useable_df[col].fillna(useable_df[col].mean(), inplace=True)
display(useable_df)

Index(['Sustainability_Score', 'Total_Renewal_Score_New', 'Last_Years_Price',
       'Auto_Renewal_Score', 'Status_Scores', 'Anchoring_Score',
       'Tenure_Scores', 'Current_Anchorings', 'Payment_Timeframe',
       'Renewal_Score_At_Release', 'Proforma_Approved_Lists', 'Tenure_Years',
       'Starting_Net', 'Starting_Vat', 'Starting_Gross',
       'Starting_Membership_Net', 'Starting_Package_Net', 'Starting_PQQ_Net',
       'Gross', 'Membership_Net', 'Package_Net', 'PQQNet', 'Total_Net_Paid',
       'Amount', 'Total_Amount', '#_of_Connection', 'Renewal_Year'],
      dtype='str')

C:\Users\GokulkannaML\AppData\Local\Temp\ipykernel_17308\1466166575.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  useable_df[col].fillna(useable_df[col].mean(), inplace=True)

,Co_Ref,Renewal_Month,Sustainability_Score,Total_Renewal_Score_New,Last_Years_Price,Auto_Renewal_Score,Status_Scores,Anchoring_Score,Tenure_Scores,Proforma_Auto_Renewal,...,Prospect_Outcome,Payment_Method,Amount,Total_Amount,Connection_Group,Tenure_Group,#_of_Connection,Anchor_Group,Renewal_Year,DateTime_Out
0,VT6174,01-11-2024,8.0,42.5,799.0,9.0,9.0,7.5,9.0,True,...,Won,CARD,919,799.0,1,3,1.0,1,2024,01-11-2024
1,VD3828,01-08-2025,8.0,41.5,799.0,9.0,9.0,7.5,8.0,True,...,Won,CARD,919,799.0,1,1,1.0,1,2025,01-08-2025
2,DV8120,01-03-2025,8.0,33.0,799.0,8.0,0.0,7.5,9.5,True,...,Won,CARD,799,799.0,1,4+,1.0,1,2025,01-03-2025
3,EZ9894,01-06-2025,9.5,44.5,799.0,9.0,9.0,7.5,9.5,True,...,Won,CARD,799,799.0,1,4+,1.0,1,2025,01-06-2025
4,FA8957,01-03-2025,9.5,42.5,799.0,9.0,8.0,7.5,8.5,True,...,Won,CARD,799,799.0,1,3,1.0,1,2025,01-03-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122077,VI6211,01-04-2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,539,539.0,NaN,NaN,0.0,NaN,2023,01-04-2023
122078,NI7208,01-06-2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,539,539.0,NaN,NaN,0.0,NaN,2023,01-06-2023
122079,DO6023,01-09-2023,8.0,33.0,539.0,9.0,0.0,7.5,8.5,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-09-2023
122080,KR5815,01-08-2023,8.0,40.5,539.0,9.0,7.0,7.5,9.0,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-08-2023
122081,MA8737,01-07-2023,8.0,42.5,539.0,9.0,9.0,7.5,9.0,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-07-2023

In [97]:
columns= useable_df.columns
total_count=len(useable_df)
columns_with_min_null=[]
for x in columns:
   
    null_count= (billings_df[x].isnull().sum())
    print(x ,"   ", "Total count:" , total_count,"   ", "NUll :", null_count , end="  |  ")
    print()

Co_Ref     Total count: 122082     NUll : 0  |
Renewal_Month     Total count: 122082     NUll : 0  |
Sustainability_Score     Total count: 122082     NUll : 0  |
Total_Renewal_Score_New     Total count: 122082     NUll : 0  |
Last_Years_Price     Total count: 122082     NUll : 9090  |
Auto_Renewal_Score     Total count: 122082     NUll : 0  |
Status_Scores     Total count: 122082     NUll : 0  |
Anchoring_Score     Total count: 122082     NUll : 0  |
Tenure_Scores     Total count: 122082     NUll : 0  |
Proforma_Auto_Renewal     Total count: 122082     NUll : 18052  |
Proforma_World_Pay_Token     Total count: 122082     NUll : 18052  |
Proforma_Date     Total count: 122082     NUll : 304  |
Current_Anchorings     Total count: 122082     NUll : 0  |
Current_Anchor_List     Total count: 122082     NUll : 25957  |
Payment_Timeframe     Total count: 122082     NUll : 20856  |
Registration_Date     Total count: 122082     NUll : 1018  |
Proforma_Account_Stage     Total count: 122082     NUll : 9229  |
Proforma_Audit_Status     Total count: 122082     NUll : 9229  |
Current_Auto_Renewal_Flag     Total count: 122082     NUll : 0  |
Current_World_Pay_Token     Total count: 122082     NUll : 0  |
Renewal_Score_At_Release     Total count: 122082     NUll : 126  |
Proforma_Membership_Status     Total count: 122082     NUll : 126  |
Proforma_Approved_Lists     Total count: 122082     NUll : 126  |
Tenure_Years     Total count: 122082     NUll : 1018  |
Band     Total count: 122082     NUll : 24  |
Prospect_Renewal_Date     Total count: 122082     NUll : 0  |
Closed_Date     Total count: 122082     NUll : 8188  |
Prospect_Status     Total count: 122082     NUll : 0  |
Starting_Net     Total count: 122082     NUll : 0  |
Starting_Vat     Total count: 122082     NUll : 0  |
Starting_Gross     Total count: 122082     NUll : 0  |
Starting_Membership_Net     Total count: 122082     NUll : 0  |
Starting_Package_Net     Total count: 122082     NUll : 0  |
Starting_PQQ_Net     Total count: 122082     NUll : 0  |
Gross     Total count: 122082     NUll : 0  |
Membership_Net     Total count: 122082     NUll : 0  |
Package_Net     Total count: 122082     NUll : 0  |
PQQNet     Total count: 122082     NUll : 0  |
Total_Net_Paid     Total count: 122082     NUll : 20856  |
Prospect_Outcome     Total count: 122082     NUll : 0  |
Payment_Method     Total count: 122082     NUll : 0  |
Amount     Total count: 122082     NUll : 0  |
Total_Amount     Total count: 122082     NUll : 0  |
Connection_Group     Total count: 122082     NUll : 126  |
Tenure_Group     Total count: 122082     NUll : 1018  |
#_of_Connection     Total count: 122082     NUll : 126  |
Anchor_Group     Total count: 122082     NUll : 126  |
Renewal_Year     Total count: 122082     NUll : 0  |
DateTime_Out     Total count: 122082     NUll : 0  |

In [88]:
useable_df.fillna({col: useable_df[col].mean() for col in numerical_columns}, inplace=True)

,Co_Ref,Renewal_Month,Sustainability_Score,Total_Renewal_Score_New,Last_Years_Price,Auto_Renewal_Score,Status_Scores,Anchoring_Score,Tenure_Scores,Proforma_Auto_Renewal,...,Prospect_Outcome,Payment_Method,Amount,Total_Amount,Connection_Group,Tenure_Group,#_of_Connection,Anchor_Group,Renewal_Year,DateTime_Out
0,VT6174,01-11-2024,8.0,42.5,799.0,9,9,7.5,9.0,True,...,Won,CARD,919,799.0,1,3,1.0,1,2024,01-11-2024
1,VD3828,01-08-2025,8.0,41.5,799.0,9,9,7.5,8.0,True,...,Won,CARD,919,799.0,1,1,1.0,1,2025,01-08-2025
2,DV8120,01-03-2025,8.0,33.0,799.0,8,0,7.5,9.5,True,...,Won,CARD,799,799.0,1,4+,1.0,1,2025,01-03-2025
3,EZ9894,01-06-2025,9.5,44.5,799.0,9,9,7.5,9.5,True,...,Won,CARD,799,799.0,1,4+,1.0,1,2025,01-06-2025
4,FA8957,01-03-2025,9.5,42.5,799.0,9,8,7.5,8.5,True,...,Won,CARD,799,799.0,1,3,1.0,1,2025,01-03-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122077,VI6211,01-04-2023,8.0,33.5,539.0,9,0,7.5,9.0,NaN,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-04-2023
122078,NI7208,01-06-2023,8.0,30.5,539.0,8,0,7.5,7.0,NaN,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-06-2023
122079,DO6023,01-09-2023,8.0,33.0,539.0,9,0,7.5,8.5,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-09-2023
122080,KR5815,01-08-2023,8.0,40.5,539.0,9,7,7.5,9.0,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-08-2023
122081,MA8737,01-07-2023,8.0,42.5,539.0,9,9,7.5,9.0,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-07-2023

In [95]:
useable_df.isnull().sum()
useable_df.select_dtypes(include=['float64', 'int64']).columns

Index(['Sustainability_Score', 'Total_Renewal_Score_New', 'Last_Years_Price',
       'Auto_Renewal_Score', 'Status_Scores', 'Anchoring_Score',
       'Tenure_Scores', 'Current_Anchorings', 'Payment_Timeframe',
       'Renewal_Score_At_Release', 'Proforma_Approved_Lists', 'Tenure_Years',
       'Starting_Net', 'Starting_Vat', 'Starting_Gross',
       'Starting_Membership_Net', 'Starting_Package_Net', 'Starting_PQQ_Net',
       'Gross', 'Membership_Net', 'Package_Net', 'PQQNet', 'Total_Net_Paid',
       'Amount', 'Total_Amount', '#_of_Connection', 'Renewal_Year'],
      dtype='str')

In [ ]:

# Define the columns to clean and handle nulls for categorical data
selected_columns = [
    'Prospect_Outcome', 'Total_Renewal_Score_New', 'Sustainability_Score',
    'Auto_Renewal_Score', 'Status_Scores', 'Anchoring_Score', 'Tenure_Scores',
    'Tenure_Years', 'Current_Auto_Renewal_Flag', 'Proforma_Auto_Renewal',
    'Last_Years_Price', 'Total_Net_Paid', 'Payment_Method', 'Band',
    'Tenure_Group', 'Connection_Group', 'Anchor_Group', 'Payment_Timeframe',
    'Proforma_Audit_Status'
]

# Keep only the selected columns available in the current dataframe
selected_columns = [col for col in selected_columns if col in useable_df.columns]
print('Selected columns available for cleaning:', selected_columns)

# Work on a fresh copy to avoid modifying prior notebook cells indirectly
cleaned_df = useable_df[selected_columns].copy()

# Identify categorical columns and numeric columns among the selected subset
categorical_columns = cleaned_df.select_dtypes(include=['object', 'category','str']).columns.tolist()
numeric_columns = cleaned_df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print('Categorical columns:', categorical_columns)
print('Numeric columns:', numeric_columns)

# Fill missing values for categorical columns with the mode if available, else 'Unknown'
for col in categorical_columns:
    if cleaned_df[col].isnull().any():
        mode_value = cleaned_df[col].mode(dropna=True)
        fill_value = mode_value.iloc[0] if not mode_value.empty else 'Unknown'
        cleaned_df[col].fillna(fill_value, inplace=True)
        

cleaned_df.dropna(subset=['Band','Proforma_Auto_Renewal'], inplace=True)
cleaned_df.fillna({col: 'Unknown' for col in cleaned_df.columns if col in ['Tenure_Group']}, inplace=True)
        

# Preserve the cleaned dataframe for later use
useable_df[selected_columns] = cleaned_df

# Show summary of null counts after cleaning
cleaned_df.isnull().sum()

# cleaned_df.head(20)

Selected columns available for cleaning: ['Prospect_Outcome', 'Total_Renewal_Score_New', 'Sustainability_Score', 'Auto_Renewal_Score', 'Status_Scores', 'Anchoring_Score', 'Tenure_Scores', 'Tenure_Years', 'Current_Auto_Renewal_Flag', 'Proforma_Auto_Renewal', 'Last_Years_Price', 'Total_Net_Paid', 'Payment_Method', 'Band', 'Tenure_Group', 'Connection_Group', 'Anchor_Group', 'Payment_Timeframe', 'Proforma_Audit_Status']
Categorical columns: ['Prospect_Outcome', 'Current_Auto_Renewal_Flag', 'Proforma_Auto_Renewal', 'Payment_Method', 'Band', 'Tenure_Group', 'Connection_Group', 'Anchor_Group', 'Proforma_Audit_Status']
Numeric columns: ['Total_Renewal_Score_New', 'Sustainability_Score', 'Auto_Renewal_Score', 'Status_Scores', 'Anchoring_Score', 'Tenure_Scores', 'Tenure_Years', 'Last_Years_Price', 'Total_Net_Paid', 'Payment_Timeframe']

C:\Users\GokulkannaML\AppData\Local\Temp\ipykernel_17308\2656243897.py:30: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  cleaned_df[col].fillna(fill_value, inplace=True)

Prospect_Outcome             0
Total_Renewal_Score_New      0
Sustainability_Score         0
Auto_Renewal_Score           0
Status_Scores                0
Anchoring_Score              0
Tenure_Scores                0
Tenure_Years                 0
Current_Auto_Renewal_Flag    0
Proforma_Auto_Renewal        0
Last_Years_Price             0
Total_Net_Paid               0
Payment_Method               0
Band                         0
Tenure_Group                 0
Connection_Group             0
Anchor_Group                 0
Payment_Timeframe            0
Proforma_Audit_Status        0
dtype: int64

In [91]:
display(useable_df)
useable_df.isnull().sum()

,Co_Ref,Renewal_Month,Sustainability_Score,Total_Renewal_Score_New,Last_Years_Price,Auto_Renewal_Score,Status_Scores,Anchoring_Score,Tenure_Scores,Proforma_Auto_Renewal,...,Prospect_Outcome,Payment_Method,Amount,Total_Amount,Connection_Group,Tenure_Group,#_of_Connection,Anchor_Group,Renewal_Year,DateTime_Out
0,VT6174,01-11-2024,8.0,42.5,799.0,9.0,9.0,7.5,9.0,True,...,Won,CARD,919,799.0,1,3,1.0,1,2024,01-11-2024
1,VD3828,01-08-2025,8.0,41.5,799.0,9.0,9.0,7.5,8.0,True,...,Won,CARD,919,799.0,1,1,1.0,1,2025,01-08-2025
2,DV8120,01-03-2025,8.0,33.0,799.0,8.0,0.0,7.5,9.5,True,...,Won,CARD,799,799.0,1,4+,1.0,1,2025,01-03-2025
3,EZ9894,01-06-2025,9.5,44.5,799.0,9.0,9.0,7.5,9.5,True,...,Won,CARD,799,799.0,1,4+,1.0,1,2025,01-06-2025
4,FA8957,01-03-2025,9.5,42.5,799.0,9.0,8.0,7.5,8.5,True,...,Won,CARD,799,799.0,1,3,1.0,1,2025,01-03-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122077,VI6211,01-04-2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,539,539.0,NaN,NaN,0.0,NaN,2023,01-04-2023
122078,NI7208,01-06-2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,539,539.0,NaN,NaN,0.0,NaN,2023,01-06-2023
122079,DO6023,01-09-2023,8.0,33.0,539.0,9.0,0.0,7.5,8.5,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-09-2023
122080,KR5815,01-08-2023,8.0,40.5,539.0,9.0,7.0,7.5,9.0,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-08-2023
122081,MA8737,01-07-2023,8.0,42.5,539.0,9.0,9.0,7.5,9.0,True,...,Won,CARD,539,539.0,Independent,3,0.0,Independent,2023,01-07-2023

Co_Ref                            0
Renewal_Month                     0
Sustainability_Score          18057
Total_Renewal_Score_New       18057
Last_Years_Price              18057
Auto_Renewal_Score            18057
Status_Scores                 18057
Anchoring_Score               18057
Tenure_Scores                 18057
Proforma_Auto_Renewal         18057
Proforma_World_Pay_Token      18052
Proforma_Date                   304
Current_Anchorings                0
Current_Anchor_List           25957
Payment_Timeframe             18057
Registration_Date              1018
Proforma_Account_Stage         9229
Proforma_Audit_Status         18057
Current_Auto_Renewal_Flag     18057
Current_World_Pay_Token           0
Renewal_Score_At_Release          0
Proforma_Membership_Status      126
Proforma_Approved_Lists           0
Tenure_Years                  18057
Band                          18057
Prospect_Renewal_Date             0
Closed_Date                    8188
Prospect_Status                   0
Starting_Net                      0
Starting_Vat                      0
Starting_Gross                    0
Starting_Membership_Net           0
Starting_Package_Net              0
Starting_PQQ_Net                  0
Gross                             0
Membership_Net                    0
Package_Net                       0
PQQNet                            0
Total_Net_Paid                18057
Prospect_Outcome              18057
Payment_Method                18057
Amount                            0
Total_Amount                      0
Connection_Group              18057
Tenure_Group                  18057
#_of_Connection                   0
Anchor_Group                  18057
Renewal_Year                      0
DateTime_Out                      0
dtype: int64